---
#---------------------------------------------------
# DynamoDB Template to be deployed by Terraform.
#---------------------------------------------------
# CloudFormation Template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html
AWSTemplateFormatVersion: "2010-09-09"
Description: A very basic CloudFormation template to be used by Terraform.

Metadata:
  License: The Unlicense

Parameters:
  DynamoDBTableName:
    Description: The name of the table.
    Type: String
    AllowedPattern: "[a-zA-Z0-9-]*"
    MinLength: "1"
    MaxLength: "2048"
    ConstraintDescription: must contain only alphanumberic characters

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      BillingMode: "PAY_PER_REQUEST"
      TableClass: "STANDARD"
      AttributeDefinitions:
        - AttributeName: "UUID"
          AttributeType: "S"
        - AttributeName: "DateReceived"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "UUID"
          KeyType: "HASH"
        - AttributeName: "DateReceived"
          KeyType: "RANGE"
      Tags:
        - Key: Template Location
          Value: https://github.com/kwame-mintah/aws-cloudformation-playground
        - Key: IaC Provisioned
          Value: "False"

Outputs:
  TableName:
    Description: Table name of the newly created DynamoDB table
    Value: !Ref DynamoDBTable
